### ISSUE TITLE
only 1 page can have the same alias

### ISSUE THREAD

**Issue by Nemo64** [colorcube/auto404#1]
The alias field is defined as `unique`. Therefor this extension can't be used with multi domain sites.

**Comment by colorcube** [comment]
Indeed, that's a problem. So another simple way is needed to identify a 404 page.
What about the field 'Contains Plugin' on the Behaviour tab? That way a nice icon can be added too.

**Comment by colorcube** [comment]
You might try the current git version. It uses another field now.
See here how to define a custom 404 page:
https://github.com/colorcube/auto404/blob/master/Documentation/Usage/Index.rst

**Comment by Nemo64** [comment]
instead of trying to find a field you can use which is actually ment for something else... why not add a `group` field to the domain record to select which page is the 404 page for this domain?

**Comment by colorcube** [comment]
Thanks for your suggestion. It's not uncommon to have multiple domain records for one site, so that wouldn't fit very well.

The now implemented solution using the 'Contains Plugin' field (pages.module) is how I like it. Very little code changes and a nice page icon ;-)
I should have used that field from the beginning.

**Comment by colorcube** [comment]
Version 1.1.0 released
